select * from customer limit 10

--Business Problems

-- Q1) What is the total revenue generated by male vs female customers ?

	select 
	gender,
	sum(purchase_amount) as revenue
	from customer
	group by gender

--Q2) Which customers used a discount but still spent more the average purchase amount ?

	SELECT
    customer_id,
    purchase_amount
    FROM customer
    WHERE discount_applied = 'Yes'
    AND purchase_amount >= (
      SELECT AVG(purchase_amount) FROM customer
  );

--Q3) What are the top 5 products with the highest avg value rating ?

    SELECT
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_review_rating
	FROM customer
	GROUP BY item_purchased
	order by 2 desc
	limit 5
	
--Q4) Compare the avg Purchase amount between standard and express shipping.

	select 
	shipping_type,
	Round(avg(purchase_amount),2) AS avg_purchase_amt
	from customer
	where shipping_type in ('Standard' , 'Express')
	group by shipping_type

--Q5) DO Subscribed Customers spend more ? Compare avg spend and total revenue 
	--betweem subscribers and non-subscribers

	select
	subscription_status,
	count(customer_id) as total_customers,
	Round(avg(purchase_amount),2) as avg_spend,
	Round(sum(purchase_amount),2) as total_revenue 
	from customer
	group by subscription_status 
	order by total_revenue, avg_spend desc

--Q6) Which 5 products have the highest percentage of purchase with discounts applied ?

	
	SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
	FROM customer
	GROUP BY item_purchased
	ORDER BY discount_rate DESC
	LIMIT 5;

--Q7) Segments customer into new, Returning , and loyal based ontheir total
--    number of previous purchasees, and show the count of each segment.

	with customer_type as (
	select
	customer_id,
	previous_purchases,
	case
		when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
		end as customer_segment
	from customer
	)

	select customer_segment,
	count(*) as "Number of customers"
	from customer_type
	group by customer_segment

--Q8) What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank,
category,
item_purchased,
total_orders
from item_counts
where item_rank <= 3

--Q9) Are customers who are repeat buyer's (more thann previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >  5
group by subscription_status


--Q10) What is revenue contribution of each age group ?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;